### ISSUE TITLE
Investigate running all System/Driver jobs together.

### ISSUE THREAD

**Issue by jkeon** [decline-cookies/anvil-unity-dots#102]
Currently we run the TaskDriver jobs that populate first, then the System jobs that Update etc.

We have the concept of a TaskFlowRoute. 

This was because before, data was consolidated by weaving in with the jobs allowing for the potential to move through chains of drivers/systems in one frame.

This was cool but dangerous because it meant that we might end up in a no-win situation where the ordering of systems resulted in a long time to move through the chain, but changing that ordering resulted in other data taking a long time. Endless nightmare scenario at the end of the project.

With the changes that all the data is consolidated at the beginning of the frame, I don't think this is relevant anymore and we might be able to do away with the concept of the route and instead just run all jobs in parallel for a given system/drivers.

**Comment by mbaker3** [comment]
Would this be a bad idea because, presumably, all of these jobs are going to compete for the same data?

**Comment by jkeon** [comment]
Before, yes. But now, not really. 

Anyone who is going to write will write to the Pending collection. 
Anyone who is going to read will read from the Live collection. 

For both of those, they will have different dependencies. 
Writers will all get a SharedWrite dependencies. 
Readers will all get a SharedRead dependency. 

This should allow most if not all jobs to be run in parallel. 

Obviously if multiple jobs need exclusive access to something like a CDFE or DynamicBuffer etc we might have some scheduling delays but overall we should be really free from that.

**Comment by mbaker3** [comment]
OK, and does this mean that we won't be able to weave non-task driver systems together?

If so, I'm not sure if that's going to be an issue or not. I'm still fighting system ordering and trying to establish some best practices so I don't know if it'll be a need. I could see issues if we end up using task drivers for rendering operations.
