### ISSUE TITLE
AccessControlledValue Dispose Method

### ISSUE THREAD

**Issue by jkeon** [decline-cookies/anvil-unity-dots#104]
An `AccessControlledValue` today just disposes the `AccessController` and tries to dispose the value inside.

```csharp
protected override void DisposeSelf()
        {
            m_AccessController.Dispose();
            (m_Value as IDisposable)?.Dispose();
            base.DisposeSelf();
        }
```

When you call `AccessControlledValue.Dispose()` you might run into a problem where the underlying data is still in flight. 

So the pattern is to acquire synchronously for disposal first:

```csharp
m_MyAccessControlledValue.Acquire(AccessType.Disposal);
m_MyAccessControlledValue.Dispose();
```

Seems error-prone to forget about this and annoying to write, should we just do it automatically in the Dispose?

```csharp
protected override void DisposeSelf()
        {
            m_AccessController.Acquire(AccessType.Disposal);
            m_AccessController.Dispose();
            (m_Value as IDisposable)?.Dispose();
            base.DisposeSelf();
        }
```

**Comment by mbaker3** [comment]
Yea, there should also probably be a `Dispose(JobHandle)` that allows you to schedule disposal just like the rest of the job friendly objects.

**Comment by jkeon** [comment]
Good point!
