### ISSUE TITLE
Create ReadOnly `AccessControlledValue`

### ISSUE THREAD

**Issue by mbaker3** [decline-cookies/anvil-unity-dots#173]
Create a wrapper type or interface (both?) for `AcccessControlledValue` (and/or) `AccessController` that only allows the ability to make read acquisitions.

This is useful for cases where a system wants to expose a value but does not want anyone to edit the collection. Today we have to accomplish this with custom methods like `NativeArray<T> AcquireMyReadonlyCollectionAsync()`

**Comment by jkeon** [comment]
This is now merged
