### ISSUE TITLE
World Moving - Remap Entity data in VirtualData/TaskDrivers

### ISSUE THREAD

**Issue by jkeon** [decline-cookies/anvil-unity-dots#42]
Raised from the concern here:

https://github.com/decline-cookies/anvil-unity-dots/pull/40#pullrequestreview-1022240666

We need to ensure we can remap `Entity` structs inside `VirtualData`/`TaskDrivers` when they move a world. 

> Can we get away with just using the existing hooks provided by [IEnvironmentLifecycleObserver](https://github.com/decline-cookies/twisted-dots/blob/main/build/TwistedDOTS/Assets/App/Scripts/Runtime/Game/Simulation/Environment/IEnvironmentLifecycleObserver.cs)?

Possibly? I think we'd probably want to run this more centrally rather than remembering to do it for every System? Although if we bake it into the `AbstractTaskDriverSystem` that might be automatic and fine. So long as you're not using `VirtualData` anywhere else... which you probably wouldn't be.

> I imagine we'll still need to iterate over all systems and move the VD over.

Agreed.

> Does this need to be main thread?

I don't think so. In order to iterate we will want access to the Data so we'll need to do an exclusive write anyway. Once we acquire that the actual job can happen off thread to remap. 

> Do we need to push the TaskDrivers into a particular state before the move?

I think we'll want them to be complete such that we have access to the exclusive write for the data. 

> Do we move the instances themselves and reconfigure their world/system refs or just the memory that backs them?

TaskDrivers and TaskDriverSystems are unique to their owning Worlds and should stay that way. WorldA has a `MoveToTaskDriverSystem` with `MoveToTaskDrivers` and WorldB has it's own `MoveToTaskDriverSystem` with `MoveToTaskDrivers`. 

We don't want to move any of that "structure" just the data inside. 

> Is there a particular player loop phase that this needs to happen in?

Probably want to do it either at the beginning or end of the frame after the Entity's have been moved and we have access to the remap data. That way no systems or taskdriver jobs are in flight.

> Will probably have to do some entity remapping since the index/version of any referenced entity will change

Yes agreed.

**Slack transcript of discussion below:**

> Jon Keon
> Ok yeah so with Entity World movement, the issue here (potentially) is that all the Entity’s move from one World to another and during that transfer, they may (or do?) get different ID’s? And that breaks the relationships that we’re managing or that Unity doesn’t know about?
> If today you have:
> A) An Entity with a Component and that Component links to another Entity does it transfer properly?
> B) An Entity with a DynamicBuffer and the elements in the Buffer link to other Entities does it transfer properly?
> C) An Entity with a Component and that Component has an UnsafeList on it that contains a link to another Entity does it transfer properly?
> I guess I’m not really sure where Unity will or won’t manage that Entity changing out from under you case.
> Regardless, two possible mitigations:
> We could write the same logic to run on all VirtualData after a world move to handle remapping the Entities properly.
> We don’t need to key on Entities. We can just Key on an int that is an ID that doesn’t change when moving across Worlds. The Entity would have a component on it that would have this ID so even if the Entity changes out from under us, the ID stays the same and thus all the VirtualData stays related.
> We would probably need to build a World level lookup upon transfer to build a mapping the other way if for some reason given an Entity you wanted to find out what its corresponding ID is. But that should be a pretty simple and quick parallel job.
> 
> 
> Mike
> when you do the move it can populate a remap array which (I believe) is myArray[oldEntityIndex] = {object that represents the new entity index/version}
> The remap array is sparsely populated and the size of the largest index's value.
> So if you have entities with index 1, 5, 30.
> You'll get a remap array with a length of 31
> ...kind of an insane optimization
> Unity will auto update all entity references in IComponentData that on an Entity (in their chunks)
> I don't know if it handles more advanced cases than that...not hard to test
> 
> 
> Jon Keon
> Ok so it seems like keying on an ID might be better for us
> 
> 
> Mike
> why? the index remapping already exists
> adding an ID to everything is a lot of overhead
> 
> 
> Jon Keon
> Not for VirtualData? A TimerInstance references Entity(34:232) but then we move worlds. That Entity isn’t still going to be 34:232 is it?
> What overhead? Only the ActorEntity needs one component that has an int on it?
> 
> 
> Mike
> Unity won't do the remap for us but we'll have the array to do the remap ourselves. We have all the info required to do the remap we just have to iterate through and do it the same way they do
> 
> 
> Jon Keon
> Ohhhhh
> Gotcha
> ok well i guess that works then
> 
> 
> Mike
> yea Unity spits out an array that describes the remaps that were required. What each entity index turned into.
> 
> 
> Jon Keon
> I figured that was what happened internally, I didn’t realize it was kept around and we could access it
> 
> 
> Mike
> Yea, there are some more advanced remap utility methods too that may be useful. I don't know what they all do though. The only documentation I've seen is from that 5argon guy and the english is so broken I don't really know what he's saying
> For actor ID int, every actor has an int? That seems like a lot of extra ints that we also have to manage for overflow and reuse available IDs. Basically Unity's entity ID system. That's why they have the Version value along with the index
> kind of crazy they blow 2 ints on that when Version could probably just be a byte and then they periodically do a normalization pass to get all indexes on the same version
> We can go through the VD move process later but I guess we have to decide how we're actually moving the data over and where we make the split of the instance kept in the old Environment vs what gets moved (At the collection level, task level ,etc...).
> 
> 
> Jon Keon
> Sure, I guess with the ID way you don’t have to bother collecting all VirtualData and gaining access to it and then iterating to update any Data that references Entities. Especially when there might be custom cases like this:
> ```
> public struct PathfindTaskResult : IKeyedData<Entity>
>     {
>         public Entity Key
>         {
>             get;
>         }
> 
>         public readonly int PathLength;
>         public readonly Entity PathPointerEntity;
> ```
> Cool, we know IKeyedData will always have Key Entity to update but how do we know about PathPointerEntity unless we write a custom remap logic for this struct or do some reflection?
> But yes I agree, we can deal with it when we get to it but I’m not worried about it. There are solutions with various pros/cons.
> 
> 
> Mike
> we'll see how Unity does it and go from there. I think they reflect on each type and store whether there is an entity reference on a type and at what offset
> 
> 
> Jon Keon
> ah ok nice
> 
> 
> Mike
> I more need to know how the move is happening and at what level of data and what state it all needs to be in
> but that's the PR discussion to have this week

**Comment by mbaker3** [comment]
Ok, yea. Having `AbstractTaskDriverSystem` or rather a project specific `AbstractTaskDriverSystem` implement `IEnvironmentLifecycleObserver` is the best approach then. Those are just hooks to let a system do work pre entity eviction and post import/adoption. The tricky part is that the `EnvironmentLifecycleSystem` owns that flow right now. I'm not sure whether we can fit the extra handling in there.

We'll either have to expand the capability of the lifecycle hooks or fit the logic into the `EnvironmentLifecycleSystem` alongside the location it does the entity move.

If we can't fit a project specific `AbstractTaskDriverSystem` subclass in because there are already implementing subclasses then I can look at making the environment lifecycle logic generic to all projects and instead call it a `WorldLifecycleSystem` or something and then having the task drivers hook into that. Long term, that probably makes more sense since entity world moving is something that anvil systems should probably support.
We may need to use write groups to help get some project specific functionality in that flow but I'm sure there are options.
