### ISSUE TITLE
Task System - Resolve Target Optimization

### ISSUE THREAD

**Issue by jkeon** [decline-cookies/anvil-unity-dots#78]
In `NodeLookup` in `PopulateWithResolveTargetDataStreams` we're building up the list in a pretty inefficient manner. 

It may never be a problem, but something to probably optimize in the future. 

Very minor right now though.

**Comment by jkeon** [comment]
Closing as no longer valid.

**Comment by mbaker3** [comment]
Just for posterity, what work invalidates this? A specific PR?

**Comment by jkeon** [comment]
Yes #142
